server:
  port: 8000


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: backend
  datasource:
    username: root
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/onlineshopping
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    rest:
      base-path: /api

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

auth:
  token:
    secret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
    expirationTime: 3600000

project:
  image: images/

#JWT Security Key
jwt_secret: cl$ksc^nas%lkdm!cz@xclk#as&dmka;s28*392da%jskd#n9827@3498%

#Swagger OpenAPI
springdoc:
  swagger-ui:
    #For sorting endpoints alphabetically
    operationsSorter: alpha
    #For sorting tags alphabetically
    tagsSorter: alpha
    #to remove doc expansion
    doc-expansion: false